before:
  hooks:
    - go mod tidy
builds:
-
  id: nextdns-nohttp3
  goos:
  - freebsd
  - netbsd
  - openbsd
  - dragonfly
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - arm
  - mips
  - mipsle
  - mips64
  - mips64le
  goarm:
  - 5
  - 6
  - 7
  gomips:
  - softfloat
  - hardfloat
  env:
  - CGO_ENABLED=0
  flags:
  - -tags=nohttp3
-
  goos:
  - freebsd
  - netbsd
  - openbsd
  - dragonfly
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
archives:
-
  format_overrides:
  -
    goos: windows
    format: zip
  files:
  - LICENSE
  - README.md
checksum:
  name_template: 'checksums.txt'
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
brews:
-
  tap:
    owner: nextdns
    name: homebrew-tap
  commit_author:
    name: NextDNS Team
    email: team@nextdns.io
  homepage: https://nextdns.io
  description: NextDNS DNS/53 to DoH Proxy
  caveats: "To install NextDNS, run the following command:

    sudo nextdns install --config <your_conf_id>

Then setup your DNS manually to 127.0.0.1 or by running:

    sudo nextdns activate
"
nfpms:
  -
    vendor: NextDNS Inc
    homepage: https://nextdns.io
    maintainer: NextDNS Team <team@nextdns.io>
    description: NextDNS DNS/53 to DoH Proxy
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    dependencies:
      - curl
    overrides:
      deb:
        scripts:
          postinstall: ".goreleaser/postinstall_deb.sh"
          preremove: ".goreleaser/preremove_deb.sh"
      rpm:
        scripts:
          postinstall: ".goreleaser/postinstall_rpm.sh"
          preremove: ".goreleaser/preremove_rpm.sh"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
