{
 "title": "NextDNS Metrics",
 "tags": [
  "nextdns",
  "prometheus",
  "dns"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total DNS Queries",
   "type": "stat",
   "description": "Total DNS queries since last NextDNS CLI restart",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nextdns_queries_total)", "legendFormat": "Queries (5m)" }
   ]
  },
  {
   "title": "Local Unique UDP Clients (5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextdns_unique_clients_udp", "legendFormat": "Unique UDP Clients" }
   ]
  },
  {
   "title": "Upstream Idle Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextdns_idle_connections_upstream",
     "legendFormat": "Idle Upstream Connections"
    }
   ]
  },
  {
   "title": "DNS Queries Last 5 Mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(nextdns_queries_total[5m])",
     "legendFormat": "Queries (5m)"
    }
   ]
  },
  {
   "title": "Local Max In-Flight UDP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nextdns_inflight_queries_local_udp_max",
     "legendFormat": "Max UDP"
    }
   ]
  },
  {
   "title": "Local Max In-Flight TCP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nextdns_inflight_queries_local_tcp_max",
     "legendFormat": "Max TCP"
    }
   ]
  },
  {
   "title": "Local In-Flight Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nextdns_inflight_queries_local_tcp",
     "legendFormat": "TCP"
    },
    {
     "expr": "nextdns_inflight_queries_local_udp",
     "legendFormat": "UDP"
    }
   ]
  },
  {
   "title": "Upstream In-Flight Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nextdns_inflight_queries_upstream_tcp",
     "legendFormat": "Upstream TCP"
    },
    {
     "expr": "nextdns_inflight_queries_upstream_udp",
     "legendFormat": "Upstream UDP"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextdns_cache_size_bytes_total", "legendFormat": "Cache Byte Size" }
   ]
  },
  {
   "title": "Cache Key Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextdns_cache_size_keys_total", "legendFormat": "Cache Byte Size" }
   ]
  },
  {
   "title": "Cache Hits vs Misses",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "nextdns_cache_hits_total", "legendFormat": "Cache Hits" },
    { "expr": "nextdns_cache_misses_total", "legendFormat": "Cache Misses" },
    { "expr": "nextdns_cache_expired_total", "legendFormat": "Cache Expired" }
   ]
  },
  {
   "title": "Cache Hits vs Misses per Time Range",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nextdns_cache_hits_total[$__rate_interval])",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "rate(nextdns_cache_misses_total[$__rate_interval])",
     "legendFormat": "Cache Misses"
    },
    {
     "expr": "rate(nextdns_cache_expired_total[$__rate_interval])",
     "legendFormat": "Cache Expired"
    }
   ]
  }
 ]
}