name: "Run GoReleaser"
description: "Centralized action for running GoReleaser"
inputs:
  args:
    description: "Arguments to pass to GoReleaser"
    required: false
runs:
  using: "composite"
  steps:
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
      with:
        distribution: goreleaser-pro
        version: 2.5.1
        args: ${{ inputs.args }}