name: Publish snapshot

on:
  workflow_run:
    workflows:
      - Snapshot
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/github-script@v4
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "dist"
            })[0];
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/dist.zip', Buffer.from(download.data));
      - run: unzip dist.zip
      - name: Publish artifacts
        run: |
          NAME="$(cat NAME)"
          rm -rf */ nextdns.rb config.yaml checksums.txt
          for f in *; do mv $f "nextdns-snapshot${f#*SNAPSHOT}"; done
          (
            echo "<html>"
            for f in *; do
              echo "<a href=\"$f\">$f</a><br>"
            done
            echo "</html>"
          ) > index.html
          aws s3 sync --no-progress --delete \
            --storage-class REDUCED_REDUNDANCY --acl public-read \
            . "s3://${AWS_BUCKET}/${NAME}/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_REPO_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_REPO_SECRET }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_BUCKET: snapshot.nextdns.io
      - name: Comment Pull Request
        uses: actions/github-script@v4
        if: github.event.workflow_run.event == 'pull_request'
        with:
          script: |
            const fs = require('fs'),
                  issue_number = Number(fs.readFileSync('PR')),
                  name = fs.readFileSync('NAME'));
            github.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📷 <a href="https://snapshot.nextdns.io/${name}">Snapshot created</a>`
            })
