name: Snapshot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.16"
      - name: Test
        run: go test -tags=http3 ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
      - name: Get name (push)
        if: github.event_name == 'push'
        run: |
          echo -n ${GITHUB_REF#refs/heads/} | tr / - > dist/NAME
      - name: Get name (pull request)
        if: github.event_name == 'pull_request'
        run: |
          echo -n pr-${{ github.event.number }} > dist/NAME
          echo -n ${{ github.event.number }} > dist/PR
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
